site_name: TerraTools
nav:
    - Home: index.md
    - About: about.md
    - API: 
        - 'TerraModel': 'api/terra_model.md'
        - properties:
            - 'Profiles': 'api/properties/profiles.md'
            - 'Attenuation': 'api/properties/attenuation.md'
            - 'PerpleX': 'api/properties/perplex.md'
            - 'Utilities': 'api/properties/utilities.md'

theme:
  name: "material"

plugins:
- search
- autorefs
- bibtex:
    bib_file: "docs/references.bib"
    bib_by_default: true
- mkdocstrings:
    handlers:
        python:
            options:
                selection_opt: true
                rendering_opt: "value"
                docstring_style: "sphinx"

markdown_extensions:
  - footnotes