site_name: TerraTools
nav:
    - Home: index.md
    - About: about.md
    - API: 
        - 'TerraModel': 'api/terra_model.md'
        - properties:
            - 'attenuation': 'api/properties/attenuation.md'

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
        python:
            options:
                selection_opt: true
                rendering_opt: "value"
                docstring_style: "sphinx"
