site_name: TerraTools
nav:
    - Home: index.md
    - About: about.md
    - Code Reference: reference/
    - Bibliography: zz_bibliography.md

theme:
  name: "material"

plugins:
- search
- autorefs
- section-index
- bibtex:
    bib_file: "docs/references.bib"
    bib_by_default: true
- mkdocstrings:
    handlers:
        python:
            options:
                selection_opt: true
                rendering_opt: "value"
                docstring_style: "sphinx"
    watch:
    - terratools
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- snippet:
        base_path: docs

markdown_extensions:
    - footnotes
    - pymdownx.snippets:
        check_paths: true
